//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyDescription("ServiceB")]
[assembly: AssemblyCompany("Solutions")]
[assembly: AssemblyProduct("ServiceB")]
[assembly: AssemblyVersion("1.0.3")]
[assembly: AssemblyFileVersion("1.0.3")]
[assembly: AssemblyCopyright("Copyright (c) 2016")]

